name = "unitn-oj-frontend"
compatibility_date = "2025-09-02"

[[d1_databases]]
binding = "DB"
database_name = "unitn_oj_local"
database_id = "LOCAL"
migrations_dir = "d1/migrations"

[vars]
APP_ENV = "dev"
AUTH_ALLOWED_DOMAIN = "studenti.unitn.it"
AUTH_TOKEN_TTL_SECONDS = "300"
AUTH_SESSION_TTL_SECONDS = "604800"
AUTH_SESSION_SECRET = "dev-secret"