name = "unitn-oj-frontend"
compatibility_date = "2025-09-02"

[[d1_databases]]
binding = "DB"
database_name = "unitn_oj"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "d1/migrations"

[vars]
APP_ENV = "dev"
AUTH_ALLOWED_DOMAIN = "studenti.unitn.it"
AUTH_TOKEN_TTL_SECONDS = "300"