name = "unitn-oj-frontend"
compatibility_date = "2025-09-01"

[[d1_databases]]
binding = "DB"
database_name = "unitn_oj"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "d1/migrations"

[vars]
APP_MODE = "dev"
EMAIL_ALLOWED_DOMAIN = "studenti.unitn.it"
TOKEN_TTL_SECONDS = "300"