ALTER TABLE submissions ADD COLUMN language TEXT NOT NULL DEFAULT 'cpp23' CHECK (language IN ('c','cpp23'));
ALTER TABLE submissions ADD COLUMN time_limit_ms INTEGER NOT NULL DEFAULT 2000 CHECK (time_limit_ms BETWEEN 1 AND 600000);
ALTER TABLE submissions ADD COLUMN memory_limit_kb INTEGER NOT NULL DEFAULT 262144 CHECK (memory_limit_kb BETWEEN 1024 AND 4194304);
ALTER TABLE submissions ADD COLUMN artifact TEXT;
ALTER TABLE submissions ADD COLUMN code_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE submissions ADD COLUMN run_time_ms INTEGER;
ALTER TABLE submissions ADD COLUMN run_memory_kb INTEGER;
ALTER TABLE submissions ADD COLUMN updated_at INTEGER NOT NULL DEFAULT 0;
UPDATE submissions SET code_size = length(code), updated_at = created_at WHERE updated_at = 0;
CREATE INDEX IF NOT EXISTS idx_submissions_user_created ON submissions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_problem_created ON submissions(problem_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_open_status ON submissions(status) WHERE status IN ('queued','running');