services:
  frontend:
    image: node:20-bookworm
    container_name: unitn-oj-frontend
    working_dir: /workspace/frontend
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        set -e;
        corepack enable &&
        corepack prepare pnpm@8.15.5 --activate &&
        pnpm install &&
        pnpm build &&
        pnpm wrangler d1 migrations apply DB --local &&
        pnpm wrangler d1 execute DB --local --file d1/seed/dev_seed.sql &&
        pnpm wrangler pages dev build --local --port 8080 --ip 0.0.0.0
      "
    ports:
      - "8080:8080"
