services:
  frontend:
    image: oven/bun:latest
    container_name: unitn-oj-frontend
    working_dir: /workspace/frontend
    ports:
      - "8080:8080"
      - "4173:4173"
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        set -e;
        bun install --frozen-lockfile &&
        bun run build &&
        tail -f /dev/null
      "