services:
  unitn-oj:
    build:
      context: .
      dockerfile: Dockerfile
    image: unitn-oj-dev
    container_name: unitn-oj
    working_dir: /workspace
    ports:
      - "4173:4173"
      - "8080:8080"
    env_file:
      - .dev.env
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        set -e;
        corepack enable &&
        corepack prepare pnpm@8.15.5 --activate &&
        pnpm install &&
        pnpm -r build &&
        tail -f /dev/null
      "