services:
  frontend:
    image: node:20-bookworm
    working_dir: /workspace/frontend
    container_name: unitn-oj-frontend
    volumes: [ "..:/workspace" ]
    command: bash -lc "corepack enable && corepack prepare pnpm@8.15.5 --activate && pnpm install && pnpm build && npx wrangler pages dev build --local --port 8788 --ip 0.0.0.0"
    expose: [ "8788" ]

  proxy:
    image: caddy:2-alpine
    container_name: unitn-oj-proxy
    ports: [ "8080:8080" ]
    volumes: [ "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro" ]
    depends_on: [ "frontend" ]