services:
  frontend:
    image: node:20-bookworm
    working_dir: /workspace/frontend
    container_name: unitn-oj-frontend
    volumes: [ "..:/workspace" ]
    command: >
      bash -lc "
        corepack enable &&
        corepack prepare pnpm@8.15.5 --activate &&
        pnpm install &&
        pnpm build &&
        npx wrangler types --path=/workspace/frontend/functions/types.d.ts &&
        npx wrangler pages dev build --local --port 8080 --ip 0.0.0.0
      "
    ports: [ "8080:8080" ]