services:
  unitn-oj:
    image: node:20-bookworm
    container_name: unitn-oj
    working_dir: /workspace/frontend
    ports:
      - "4173:4173"
      - "8080:8080"
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        set -e;
        corepack enable &&
        corepack prepare pnpm@8.15.5 --activate &&
        pnpm install --frozen-lockfile &&
        pnpm build &&
        tail -f /dev/null
      "