FROM node:20-bookworm

RUN set -eux; \
  apt-get update; \
  apt-get install -y --no-install-recommends wget gnupg lsb-release ca-certificates software-properties-common; \
  wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor >/usr/share/keyrings/hashicorp-archive-keyring.gpg; \
  echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
    >/etc/apt/sources.list.d/hashicorp.list; \
  apt-get update; \
  apt-get install -y terraform; \
  terraform -v; \
  rm -rf /var/lib/apt/lists/*