name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: oven-sh/setup-bun@latest
        with:
          bun-version: latest
      - uses: actions/setup-node@latest
        with:
          node-version: latest
      - working-directory: frontend
        run: bun install --frozen-lockfile
      - working-directory: frontend
        run: bun ci:check