name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: |
            frontend/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm -r run check:ci